Interacao-Humano-Computador/2023.1-DetranGO

- docs/reunioes/reuniao1.md
| Issue |
|:-----:|
|fixes #6 |
Correção de erros de português na ata da primeira reunião que passaram despercebidos anteriormente.
#6 
@PedroFMuniz
> review: correção de erros de portugues

- docs/planejamento/design.md
- docs/reunioes/reuniao1.md
- docs/reunioes/reuniao2.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #|
Criação da ata da segunda reunião do projeto e correções na ata anterior.
@phmelosilva
> create: ata da reunião 2

- docs/planejamento/cronograma_executado.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #21 |
Criação do cronograma executado da etaoa 1 do projeto e indexação no site.
Se implementado, este pull request finaliza a issue #21 
@uMorbeck
> create: cronograma executado etapa 1

- docs/apresentacoes/1a_apresentacao.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #23 |
Adicionada a página da apresentação da etapa 1 do projeto, com vídeo e slides incorpoados, bem como um checklist da primeira etapa.
#23 
> Create: pagina da apresentacao da 1a etapa

- docs/planejamento/metodologia.md
| Issue |
|:-----:|
|fixes #28 |
Correções de erros na seção de metodologias
@PedroFMuniz
> Review: correções de padrões

- docs/planejamento/sites_avaliados/sites_avaliados.md
| Issue |
|:-----:|
|fixes #28 |
> edit: Adiciona resumo SSALTO na página de sitios avaliados

- docs/reunioes/reuniao3.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #|
Adição da ata da terceira reunião.
@PedroFMuniz
> Create: ata da reuniao 3

- docs/planejamento/sites_avaliados/avaliacao_SSALTO.md
| Issue |
|:-----:|
|fixes #32 |
> edit: Padroniza tabelas da avaliação SSAlto.

- docs/planejamento/site_escolhido.md
| Issue |
|:-----:|
|fixes #41 |
Foi adicionado uma breve descrição sobre qual o usuário que pretendemos atingir
#41 
@phmelosilva
> Update: adicionando usuários em site escolhido

- docs/analise_requisitos/aspectos_eticos.md
- docs/planejamento/sites_avaliados/avaliacao_SSALTO.md
- docs/reunioes/reuniao3.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #35 |
Criação do artefato de aspectos éticos e adição no github pages.
closes #35 
@PedroFMuniz
> Aspectos éticos

- docs/planejamento/cronograma.md
- docs/planejamento/cronograma_executado.md
- docs/planejamento/cronogramas_anteriores.md
| Issue |
|:-----:|
|fixes #43| 
Atuallizações no cronograma de acordo com a issue #43. 
#43 
> Ajustes cronograma

- docs/analise_requisitos/cenarios.md
- docs/analise_requisitos/perfilUsuario.md
- docs/apresentacoes/2a_apresentacao.md
- docs/planejamento/cronograma_executado.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #39 |
Ajustes solicitados em reunião e adição da gravação
#39 
> Ajustes finais

- docs/planejamento/cronograma_executado.md
Nome do João Morbeck na análise de tarefas
> update: mudanca analise de tarefas

- docs/reunioes/reuniao4.md
- mkdocs.yml
Adição da ata da reunião de 09/05
> Ata reuniao 08 05

- docs/planejamento/cronograma_executado.md
| Issue |
|:-----:|
|fixes #|
Criação do cronograma executado da etapa 3
@MastroCoder
> Create: cronograma executado etapa 3

- docs/apresentacoes/2a_apresentacao.md
- docs/apresentacoes/3a_apresentacao.md
- mkdocs.yml
Criação da página da terceira apresentação
> create: pagina da terceira apresentacao

- docs/reunioes/reuniao5.md
- mkdocs.yml
> create: ata reuniao 15-05

- docs/dad/nivel1/analise_tarefas/planejamento_analise_tarefas.md
- docs/design_avaliacao/nivel1/analise_tarefas/planejamento_analise_tarefas.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #69 |
Redação do planejamento da análise de tarefas.
#69 
> create: plan avaliacao analise de tarefas

- docs/design_avaliacao/nivel2/prototipoPapel/planejamentoAvaliacao.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #80 |
Elaboração do artefato para o planejamento da avaliação do protótipo de papel.
fixes #80
@MastroCoder
> create: Artefato para o planejamento da avaliação do protótipo de papel

- docs/design_avaliacao/nivel2/prototipoPapel/planejamentoAvaliacao.md
- docs/design_avaliacao/nivel2/prototipoPapel/relatoResultados.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #81 |
Criação do planejamento do relato dos resultados do protótipo de papel.
#81 
@PedroFMuniz
> create: relato resultados prototipo papel

- docs/design_avaliacao/nivel1/storyboards/storyboard_relato.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #78|
Artefato com o relato da avaliação dos Storyboards.
#78 
@amanda-noda
> Relato storyboards

- docs/apresentacoes/5a_apresentacao.md
- docs/planejamento/cronograma_executado.md
Criação da página da apresentação da etapa 5 e ajustes no cronograma executado
@amanda-noda
> create: pagina quinta apresentacao + cronograma

- docs/verificacao/teste/caract_da_plataforma.md
- docs/verificacao/teste/planejamentoA_tarefas.md
- docs/verificacao/teste/principios_gerais_de_projeto.md
- docs/verificacao/teste/relato_tarefas.md
| Issue |
|:-----:|
|fixes #|
Adiciona verificação etapa 6.1 características da plataforma, planejamento da análise de tarefas, relato da análise de tarefas e princípios gerais do projeto
> Verificação etapa 6.1 - Amanda

- docs/verificacao/teste/analise_de_tarefas.md
- docs/verificacao/teste/aspectos_eticos.md
- docs/verificacao/teste/perfil_de_usuario.md
- docs/verificacao/teste/personas.md
- docs/verificacao/teste/planejamento.md
- docs/verificacao/teste/planejamentoR_tarefas.md
- docs/verificacao/teste/processo_de_design.md
| Issue |
|:-----:|
|fixes #|
Verificação dos artefatos designados e mudanças necessárias em outros
@PedroFMuniz
> create: verificacoes felipe

- docs/verificacao/teste/guia_de_estilo.md
- docs/verificacao/teste/planejamentoA_storyboard.md
- docs/verificacao/teste/planejamentoR_storyboard.md
| Issue |
|:-----:|
|fixes #|
Adição do conteúdo das páginas de verificação dos artefatos guia de estilo, planejamento de avaliação de storyboard e planejamento de resultados de relato do storyboard
@amanda-noda
> Verificação de guia de estilo e planejamento de avaliação e relato do storyboard

- docs/apresentacoes/6-1a_apresentacao.md
- docs/reunioes/reuniao6.md
- mkdocs.yml
Criação da ata de reunião e página da apresentação do dia 05/06/2023
> create: ata reuniao 06/05 e pagina apresentacao 6

- docs/design_avaliacao/nivel3/prototipoAlta/plan_avaliacao.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #95 |
Foi elaborado e criado o artefato que descreve o planejamento da avaliação do protótipo de alta fidelidade
closes #95 
@phmelosilva
> Create: artefato do planejamento da avaliação do protótipo de alta

- docs/design_avaliacao/nivel3/prototipoAlta/plan_relato.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #97 |
Foi criado o artefato de planejamento do relato de resultados do protótipo de alta fidelidade
#97 
Avalie se é necessário linkar com o conteúdo do livro, na introdução por exemplo
@PedroFMuniz
> Planejamento do relato de resultados do protótipo de alta fidelidade

- docs/design_avaliacao/nivel2/prototipoPapel/planejamentoAvaliacao.md
- docs/design_avaliacao/nivel2/prototipoPapel/relatoResultados.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #98|
Criado e adicionado artefato para o relato dos resultados do protótipo de papel.
Fixes #98 
> Relato dos resultados protótipo de papel

- docs/apresentacoes/7a_apresentacao.md
- docs/reunioes/reuniao7.md
- mkdocs.yml
Criação da ata da reunião de 12/06/2023 e da página de apresentação da etapa 7.
> create: ata 12-06 e pagina da apresentacao 7

- docs/analise_requisitos/analise_de_tarefas.md
| Issue |
|:-----:|
|fixes #|
Foi realizado a adição de outra análise de tarefa dentro do artefato de análise de tarefas assim como foi proposto na verificação do artefato.
@MastroCoder
> Update: Adição da análise GOMS

- docs/design_avaliacao/nivel3/prototipoAlta/relato_resultados.md
- mkdocs.yml
Criado artefato para o relato dos resultados, as tabelas do teste 2 estão vazias pois serão preenchidas pelo @phmelosilva 
> create: artefato para o relato dos resultados

- docs/analise_requisitos/caracteristicas_para_plataforma.md
Correções do artefato de características da plataforma.
@phmelosilva
> update: correcao caracteristicas plataforma

- docs/apresentacoes/8a_apresentacao.md
- docs/planejamento/cronograma_executado.md
- mkdocs.yml
Adição cronogramas executados e apresentação etapa 8
> update: cronogramas realizados + ent. 8

- docs/entrega_final.md
- mkdocs.yml
| Issue |
|:-----:|
|fixes #|
Artefato que contém o conteúdo a respeito da entrega final da disciplina
> Entrega Final

- docs/apresentacoes/9a_apresentacao.md
> create: apresentacao 9
